social_app/apps/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

social_app/apps/posts/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/like/', PostLikeView.as_view(), name='post_like'),
    path('post/get_comments/', GetCommentsView.as_view(), name='get_comments'),
    path('post/comment/', PostCommentView.as_view(), name='post_comment'),
]

social_app/apps/user_authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'user_authentication'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password-change'),
]

social_app/social_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('user_auth/', include('apps.user_authentication.urls', namespace='user_auth')),
    path('user_profile/', include('apps.user_profile.urls', namespace='user_profile')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('follows/', include('apps.follows.urls', namespace='follows')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_app/apps/core/models.py
from django.db import models

# Create your models here.

social_app/apps/core/views.py
from django.views import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        template = 'core/index.html'
        return render(request, template)

social_app/apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Other head elements -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/7b32716cc8.js" crossorigin="anonymous"></script>
    {% block style %}{% endblock %}
</head>
<body style="padding-top: 120px; padding-bottom: 50px;">
    <header>
        <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark">
            <div class="container">
              <a class="navbar-brand" href="{% url 'posts:home' %}">Social App</a>
              <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                      <a class="nav-link {% if request.resolver_match.view_name == 'posts:home' %}active{% endif %}" href="{% url 'posts:home' %}">Home
                          <span class="visually-hidden">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.resolver_match.view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Add Post
                          <span class="visually-hidden">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.resolver_match.view_name == 'follows:user-list' %}active{% endif %}" href="{% url 'follows:user-list' %}">Recommend Users
                          <span class="visually-hidden">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.resolver_match.view_name == 'follows:following-list' %}active{% endif %}" href="{% url 'follows:following-list' %}">Following
                          <span class="visually-hidden">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.resolver_match.view_name == 'follows:follower-list' %}active{% endif %}" href="{% url 'follows:follower-list' %}">Followers
                          <span class="visually-hidden">(current)</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.resolver_match.view_name == 'user_profile:profile' %}active{% endif %}" href="{% url 'user_profile:profile' %}">Profile
                          <span class="visually-hidden">(current)</span>
                      </a>
                  </li>                
                  <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_auth:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_auth:login' %}">Log In</a>
                  </li> -->
                </ul>
                <!-- <form class="d-flex">
                  <input class="form-control me-sm-2" type="search" placeholder="Search">
                  <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form> -->
              </div>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}{% endblock %}
    </main>
    
    <footer>
        <!-- Footer content -->
    </footer>
    
    <!-- Common JavaScript files, etc. -->
    {% block script %}{% endblock %}
</body>
</html>

social_app/apps/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <!-- Content specific to the index page -->
    <div class="clearfix">
        <div class="page-header">
            <h1>Welcome to My Website!</h1>
            <p>Check out our latest posts:</p>
        </div>
    </div>
    <!-- Rest of the content -->
{% endblock %}