social_app/apps/posts/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/like/', PostLikeView.as_view(), name='post_like'),
    path('post/get_comments/', GetCommentsView.as_view(), name='get_comments'),
    path('post/comment/', PostCommentView.as_view(), name='post_comment'),
]

social_app/social_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('user_auth/', include('apps.user_authentication.urls', namespace='user_auth')),
    path('user_profile/', include('apps.user_profile.urls', namespace='user_profile')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('follows/', include('apps.follows.urls', namespace='follows')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_app/apps/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', through='Like')
    comments = models.ManyToManyField(User, related_name='commented_posts', through='Comment')

    def __str__(self):
        return f"Post #{self.id} by {self.author.username}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} likes {self.post}"
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username

social_app/apps/posts/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']

social_app/apps/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from .models import Post, Like, Comment
from apps.user_authentication.models import Profile
from apps.follows.models import Follow
from .forms import *
from .serializers import CommentSerializer
from rest_framework.views import APIView
from rest_framework.response import Response


class PostListView(LoginRequiredMixin, ListView):
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 10  # Number of posts to display per page

    def get_queryset(self):
        # Get the current user
        user = self.request.user

        # Get the authors that the current user is following
        following_authors = Follow.objects.filter(from_user=user).values_list('to_user', flat=True)

        # Retrieve posts from the following authors and the current user
        posts = Post.objects.filter(Q(author__in=following_authors) | Q(author=user)).order_by('-created_at')

        return posts


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'posts/post_create.html'
    form_class = PostCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:home')
    

class PostLikeView(View):
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        user = request.user

        if user in post.likes.all():
            # User has already liked the post, handle unlike action
            like = Like.objects.get(user=user, post=post)
            like.delete()
            liked = False
        else:
            # User has not liked the post, handle like action
            like = Like(user=user, post=post)
            like.save()
            liked = True

        response_data = {
            'like_count': post.likes.count(),
            'button_text': 'Unlike' if liked else 'Like'
        }

        return JsonResponse(response_data)


class PostCommentView(APIView):
    def post(self, request):
        post_id = request.data.get('post_id')
        content = request.data.get('content')
        # Create the comment
        comment = Comment.objects.create(post_id=post_id, user=request.user, content=content)
        # Serialize the comment
        serializer = CommentSerializer(comment)
        # Return the serialized comment as JSON response
        return Response({'comment': serializer.data})
    
    
class GetCommentsView(APIView):
    def get(self, request):
        post_id = request.GET.get('post_id')
        comments = Comment.objects.filter(post_id=post_id)
        serialized_comments = CommentSerializer(comments, many=True).data
        comments_html = render_to_string('posts/comments.html', {'comments': serialized_comments})
        return Response({'comments_html': comments_html})

social_app/templates/posts/comments.html
{% for comment in comments %}
    <div class="comment">
        <div style="display: flex; align-items: center;">
            <div style="width: 40px; height: 40px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
                <img src="{{ comment.user.profile.profile_picture }}" alt="Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">
            </div>
            <h5 class="m-0 mx-2">{{ comment.user.username }}</h5>
        </div>
        <p>{{ comment.content }}</p>
        <p class="comment-info">{{ comment.created_at }}</p>
    </div>
{% endfor %}

social_app/templates/posts/post_card.html
<!-- post-card.html -->
<div class="card mt-3 mb-3">
    <div class="card-body pb-0">
        <div class="">
            {% with post.author.profile as profile %}
            <div style="display: flex; align-items: center;">
                {% if profile.profile_picture %}
                {% if profile.profile_picture.width == profile.profile_picture.height %}
                <div style="width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
                    <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" style="width: 100%; height: 100%; object-fit: cover; border-radius: 50%;">
                </div>
                {% else %}
                <div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
                    <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">
                </div>
                {% endif %}
                {% else %}
                <img src="/media/profile_pictures/default.jpg" alt="Default Picture" style="width: 50px; border-radius: 50%; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
                {% endif %}
                <h4 style="margin-left: 10px;">{{ post.author.username }}</h4>
            </div>
            {% endwith %}
        </div>
        <p class="my-2">{{ post.content }}</p>
        {% if post.image %}
        <img src="{{ post.image.url }}" alt="Post Image" class="w-100">
        {% endif %}
        <p class="mb-2">{{ post.created_at }}</p>
        <p class="mb-2" id="like-count-{{ post.id }}">Total Likes: {{ post.likes.count }}</p>
        <p class="mb-2" id="like-count-{{ post.id }}">Total Comments: {{ post.comments.count }}</p>
    </div>
    <div class="card-footer d-flex justify-content-between align-items-center pt-0">
        <form class="like-form" data-post-id="{{ post.id }}" action="{% url 'posts:post_like' post.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">
                {% if request.user in post.likes.all %}
                <i class="fas fa-heart"></i> Unlike
                {% else %}
                <i class="far fa-heart"></i> Like
                {% endif %}
            </button>
        </form>
        <button type="button" class="btn btn-outline-primary comment-button" data-post-id="{{ post.id }}">
            <i class="far fa-comment"></i> Comment
        </button>
    </div>
    
    <div class="comment-overlay" id="comment-overlay"></div>
    
    <div class="comment-panel" id="comment-panel-{{ post.id }}" style="display: none;">
        <div class="comments">
            <!-- Display existing comments here -->
        </div>
        <div class="comment-form-container">
            <form class="comment-form d-flex justify-content-between align-items-center" data-post-id="{{ post.id }}">
                {% csrf_token %}
                <div class="form-group w-100 me-3">
                    <textarea class="form-control" name="comment-content" rows="3" placeholder="Enter your comment"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Post</button>
            </form>
        </div>
    </div>
</div>

social_app/templates/posts/post_create.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/margin-style.css' %}">
{% endblock %}

{% block content %}
    <div class="margin margin-sm margin-md margin-lg">
        <h1>Create a Post</h1>
        <form method="post" enctype="multipart/form-data" style="display: flex; flex-direction: column;">
            {% csrf_token %}
            {{ form|crispy }}
            <div id="image-preview-container" style="display: flex; justify-content: center; align-items: center; max-width: 100%; max-height: 100%; overflow: hidden;">
            <div id="image-preview"></div> <!-- Container for the image preview -->
            </div>
            <button type="submit" class="btn btn-outline-primary" style="margin-top: 20px;">
            Upload <i class="fas fa-plus"></i>
            </button>
        </form>
    </div>
  
    <script>
        function handleImagePreview(event) {
        const reader = new FileReader();
        reader.onload = function(event) {
            const img = document.createElement("img");
            img.onload = function() {
            const canvas = document.createElement("canvas");
            const MAX_WIDTH = 800; // Maximum width for the compressed image
            const MAX_HEIGHT = 800; // Maximum height for the compressed image
            let width = img.width;
            let height = img.height;
    
            // Resize the image to fit within the maximum dimensions while maintaining aspect ratio
            if (width > height) {
                if (width > MAX_WIDTH) {
                height *= MAX_WIDTH / width;
                width = MAX_WIDTH;
                }
            } else {
                if (height > MAX_HEIGHT) {
                width *= MAX_HEIGHT / height;
                height = MAX_HEIGHT;
                }
            }
    
            canvas.width = width;
            canvas.height = height;
    
            const ctx = canvas.getContext("2d");
            ctx.drawImage(img, 0, 0, width, height);
    
            // Compress the image as a JPEG with a quality of 0.8 (adjust as needed)
            const compressedDataUrl = canvas.toDataURL("image/jpeg", 0.8);
    
            const compressedImg = document.createElement("img");
            compressedImg.style.maxWidth = "100%";
            compressedImg.style.maxHeight = "100%";
            compressedImg.src = compressedDataUrl;
            document.getElementById("image-preview").innerHTML = "";
            document.getElementById("image-preview").appendChild(compressedImg);
            };
            img.src = event.target.result;
        };
        reader.readAsDataURL(event.target.files[0]);
        }
    
        document.getElementById("id_image").addEventListener("change", handleImagePreview);
    </script>
{% endblock %}

social_app/templates/posts/post_list.html
{% extends "core/base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/margin-style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/middle-comment-panel.css' %}">
{% endblock %}

{% block content %}
<div class="margin margin-sm margin-md margin-lg">
    <div class="d-flex align-items-center justify-content-between">
      <h1>Home</h1>
      <button type="button" class="btn btn-outline-primary"><a class="nav-link" href="{% url 'posts:post_create' %}">Add Post <i class="fas fa-plus"></i></a></button>
    </div>
    <div>
        {% for post in posts %}
        {% include 'posts/post_card.html' %}
        {% empty %}
        <h1 style="text-align: center; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">No posts found!</h1>
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function() {
        $(".like-form").on("submit", function(event) {
            event.preventDefault();
            var form = $(this);
            var postId = form.data("post-id");
            var url = form.attr("action");
            var data = form.serialize();

            $.ajax({
                type: "POST",
                url: url,
                data: data,
                dataType: "json",
                success: function(response) {
                    // Update the like count
                    var likeCountElement = $("#like-count-" + postId);
                    likeCountElement.text("Total Likes: " + response.like_count);

                    // Update the like/unlike button text and icon
                    var likeButton = $(".like-form[data-post-id='" + postId + "'] button");
                    var icon = likeButton.find('i');  // Get the icon element

                    // Check the current class of the icon and change it
                    if (icon.hasClass('fas fa-heart')) {
                        icon.removeClass('fas fa-heart');
                        icon.addClass('far fa-heart');
                        likeButton.text(' Like');
                    } else {
                        icon.removeClass('far fa-heart');
                        icon.addClass('fas fa-heart');
                        likeButton.text(' Unlike');
                    }

                    likeButton.prepend(icon);
                },
                error: function(xhr, errmsg, err) {
                    console.log(xhr.status + ": " + xhr.responseText);
                }
            });
        });
        // Show/hide comment panel
        $('.comment-button').click(function() {
            var postId = $(this).data('post-id');
            var commentPanel = $('#comment-panel-' + postId);
            var commentOverlay = $('#comment-overlay');

            // Make AJAX request to retrieve comments
            $.ajax({
                url: "{% url 'posts:get_comments' %}",
                type: 'GET',
                data: { 'post_id': postId },
                success: function(response) {
                    // Update comments section
                    commentPanel.find('.comments').html(response.comments_html);

                    // Show comment panel and overlay
                    commentOverlay.show();
                    commentPanel.show();
                    // Add CSS class to body element to prevent scrolling of background content
                    $('body').addClass('no-scroll');
                },
                error: function(xhr) {
                    // Handle error
                    console.log(xhr.responseText);
                }
            });
        });

        // Close comment panel when clicking outside of it
        $('#comment-overlay').click(function(event) {
            if (event.target === this) {
                closeCommentPanel();
            }
        });

        // Submit comment form
        $('.comment-form').submit(function(event) {
            event.preventDefault(); // Prevent form submission

            var postId = $(this).data('post-id');
            var commentContent = $(this).find('textarea[name="comment-content"]').val();

            // AJAX request to post comment
            $.ajax({
                url: "{% url 'posts:post_comment' %}",
                type: 'POST',
                data: {
                    'post_id': postId,
                    'content': commentContent,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    // Append new comment to comments section
                    var commentHtml = '<div class="comment">' +
                        '<div style="display: flex; align-items: center;">' +
                            '<div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">' +
                                '<img src="' + response.comment.user.profile.profile_picture + '" alt="Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">' +
                            '</div>' +
                        '</div>' +
                        '<p>' + response.comment.content + '</p>' +
                        '<p class="comment-info">' + response.comment.created_at + ' by ' + response.comment.user.username + '</p>' +
                        '</div>';
                    $('#comment-panel-' + postId + ' .comments').append(commentHtml);

                    // Clear comment textarea
                    $('#comment-panel-' + postId + ' textarea[name="comment-content"]').val('');
                },
                error: function(xhr) {
                    // Handle error
                    console.log(xhr.responseText);
                }
            });
        });

        // Close comment panel function
        function closeCommentPanel() {
            $('.comment-panel').hide();
            $('#comment-overlay').hide();
            // Remove CSS class from body element to restore scrolling of background content
            $('body').removeClass('no-scroll');
        }
    });
    </script>
{% endblock %}