social_app/apps/posts/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/like/', PostLikeView.as_view(), name='post_like'),
    path('post/get_comments/', GetCommentsView.as_view(), name='get_comments'),
    path('post/comment/', PostCommentView.as_view(), name='post_comment'),
]

social_app/apps/user_authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'user_authentication'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password-change'),
]

social_app/apps/user_profile/urls.py
from django.urls import path
from .views import *

app_name = 'user_profile'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
    path('modify_profile/', ProfileUpdateView.as_view(), name='profile_update'),
    path('change_profile_picture/', ChangeProfilePictureView.as_view(), name='change_profile'),
]

social_app/social_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('user_auth/', include('apps.user_authentication.urls', namespace='user_auth')),
    path('user_profile/', include('apps.user_profile.urls', namespace='user_profile')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('follows/', include('apps.follows.urls', namespace='follows')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_app/apps/user_profile/models.py
from django.db import models

# Create your models here.

social_app/apps/user_profile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User
from apps.user_authentication.models import Profile
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'bio']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_picture']

social_app/apps/user_profile/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import UserProfileForm, UserForm, ProfilePictureForm
from apps.user_authentication.models import Profile
from apps.posts.models import Post

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'user_profile/profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user'] = user
        context['posts'] = user.posts.order_by('-created_at')
        return context

    
class ProfileUpdateView(LoginRequiredMixin, FormView):
    template_name = 'user_profile/profile_update.html'
    form_class = UserProfileForm
    success_url = reverse_lazy('user_profile:profile')

    def get(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        user_form = UserForm(instance=user)
        profile_form = UserProfileForm(instance=profile)
        return self.render_to_response({'user_form': user_form, 'profile_form': profile_form})

    def form_valid(self, form):
        user = self.request.user
        profile = user.profile
        user_form = UserForm(self.request.POST, instance=user)
        profile_form = UserProfileForm(self.request.POST, instance=profile)
        if user_form.is_valid():
            user_form.save()
        if profile_form.is_valid():
            profile_form.save()
        form.instance = profile
        form.save()
        return super().form_valid(form)
    
class ChangeProfilePictureView(LoginRequiredMixin, View):
    form_class = ProfilePictureForm
    template_name = 'user_profile/change_profile.html'
    success_url = 'user_profile:profile'

    def get(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        form = self.form_class(instance=profile)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        form = self.form_class(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

social_app/templates/user_profile/change_profile.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h2>Change Profile Picture</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-primary">Save</button>
  </form>
{% endblock %}

social_app/templates/user_profile/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/margin-style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/middle-comment-panel.css' %}">
<style>
    .logout-card{
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
</style>
{% endblock %}
{% block content %}
  <div style="margin-left: 25%; margin-right: 25%; text-align: center;">
    {% if user.profile.profile_picture %}
        {% if user.profile.profile_picture.width == user.profile.profile_picture.height %}
            <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" style="width: 300px; border-radius: 50%; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
        {% else %}
            <div style="width: 300px; height: 300px; border-radius: 50%; overflow: hidden; display: inline-block; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
                <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">
            </div>
        {% endif %}
    {% else %}
        <img src="/media/profile_pictures/default.jpg" alt="Default Picture" style="width: 300px; border-radius: 50%; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
    {% endif %}
    <h2 style="margin-top: 20px;">{{ user.profile.user.username }}</h2>
    <p style="margin-top: 10px;">Name: {{ user.profile.name }}</p>
    <p>Email: {{ user.profile.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>
  </div>

  <div style="text-align: center;">
    <button type="button" class="btn btn-outline-primary"><a class="nav-link" href="{% url 'user_profile:change_profile' %}">Change Profile</a></button>
    <button type="button" class="btn btn-outline-primary"><a class="nav-link" href="{% url 'user_profile:profile_update' %}">Modify Info</a></button>
    <button type="button" class="btn btn-outline-primary"><a class="nav-link" href="{% url 'user_auth:password-change' %}">Change Password</a></button>
    <button type="button" class="btn btn-outline-danger"><a class="nav-link" id="logout-button" href="{% url 'user_auth:logout' %}" onclick="confirmLogout()">Log Out</a></button>
  </div>

  <div id="confirm-card" class="modal card text-white bg-warning mb-3 logout-card" style="max-width: 370px; height: 220px;">
    <div class="card-header">
        <h3 class="mb-0">Confirm Log Out</h3>
    </div>
    <div class="card-body">
        <h5 class="mb-4">Are you sure you want to log out?</h5>
        <button type="button" class="btn btn-outline-danger" id="back-button">Back</button>
        <button type="button" class="btn btn-outline-danger" id="confirm-logout-button">Log out</button>
    </div>
  </div>

  <div class="margin margin-sm margin-md margin-lg">
    {% for post in posts %}
    {% include 'posts/post_card.html' %}
    {% empty %}
    <h1 style="text-align: center; margin-top: 2rem;">No posts found!</h1>
    {% endfor %}
  </div>
{% endblock %}

{% block script %}
<script>
    var logoutButton = document.getElementById("logout-button");
    var confirmCard = document.getElementById("confirm-card");
    var backButton = document.getElementById("back-button");
    var confirmLogoutButton = document.getElementById("confirm-logout-button");
    logoutButton.addEventListener("click", function(event) {
      event.preventDefault();
      confirmCard.style.display = "block";
    });
    backButton.addEventListener("click", function() {
      confirmCard.style.display = "none";
    });
    confirmLogoutButton.addEventListener("click", function() {
      window.location.href = logoutButton.href;
    });
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
      $(".like-form").on("submit", function(event) {
          event.preventDefault();
          var form = $(this);
          var postId = form.data("post-id");
          var url = form.attr("action");
          var data = form.serialize();

          $.ajax({
              type: "POST",
              url: url,
              data: data,
              dataType: "json",
              success: function(response) {
                  // Update the like count
                  var likeCountElement = $("#like-count-" + postId);
                  likeCountElement.text("Total Likes: " + response.like_count);

                  // Update the like/unlike button text and icon
                  var likeButton = $(".like-form[data-post-id='" + postId + "'] button");
                  var icon = likeButton.find('i');  // Get the icon element

                  // Check the current class of the icon and change it
                  if (icon.hasClass('fas fa-heart')) {
                      icon.removeClass('fas fa-heart');
                      icon.addClass('far fa-heart');
                      likeButton.text(' Like');
                  } else {
                      icon.removeClass('far fa-heart');
                      icon.addClass('fas fa-heart');
                      likeButton.text(' Unlike');
                  }

                  likeButton.prepend(icon);
              },
              error: function(xhr, errmsg, err) {
                  console.log(xhr.status + ": " + xhr.responseText);
              }
          });
      });
      // Show/hide comment panel
      $('.comment-button').click(function() {
          var postId = $(this).data('post-id');
          var commentPanel = $('#comment-panel-' + postId);
          var commentOverlay = $('#comment-overlay');

          // Make AJAX request to retrieve comments
          $.ajax({
              url: "{% url 'posts:get_comments' %}",
              type: 'GET',
              data: { 'post_id': postId },
              success: function(response) {
                  // Update comments section
                  commentPanel.find('.comments').html(response.comments_html);

                  // Show comment panel and overlay
                  commentOverlay.show();
                  commentPanel.show();
                  // Add CSS class to body element to prevent scrolling of background content
                  $('body').addClass('no-scroll');
              },
              error: function(xhr) {
                  // Handle error
                  console.log(xhr.responseText);
              }
          });
      });

      // Close comment panel when clicking outside of it
      $('#comment-overlay').click(function(event) {
          if (event.target === this) {
              closeCommentPanel();
          }
      });

      // Submit comment form
      $('.comment-form').submit(function(event) {
          event.preventDefault(); // Prevent form submission

          var postId = $(this).data('post-id');
          var commentContent = $(this).find('textarea[name="comment-content"]').val();

          // AJAX request to post comment
          $.ajax({
              url: "{% url 'posts:post_comment' %}",
              type: 'POST',
              data: {
                  'post_id': postId,
                  'content': commentContent,
                  'csrfmiddlewaretoken': '{{ csrf_token }}'
              },
              success: function(response) {
                  // Append new comment to comments section
                  var commentHtml = '<div class="comment">' +
                      '<div style="display: flex; align-items: center;">' +
                          '<div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">' +
                              '<img src="' + response.comment.user.profile.profile_picture + '" alt="Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">' +
                          '</div>' +
                      '</div>' +
                      '<p>' + response.comment.content + '</p>' +
                      '<p class="comment-info">' + response.comment.created_at + ' by ' + response.comment.user.username + '</p>' +
                      '</div>';
                  $('#comment-panel-' + postId + ' .comments').append(commentHtml);

                  // Clear comment textarea
                  $('#comment-panel-' + postId + ' textarea[name="comment-content"]').val('');
              },
              error: function(xhr) {
                  // Handle error
                  console.log(xhr.responseText);
              }
          });
      });

      // Close comment panel function
      function closeCommentPanel() {
          $('.comment-panel').hide();
          $('#comment-overlay').hide();
          // Remove CSS class from body element to restore scrolling of background content
          $('body').removeClass('no-scroll');
      }
  });
</script>
{% endblock %}

social_app/templates/user_profile/profile_update.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h2>Update Profile</h2>
  <form method="post">
    {% csrf_token %}
    {{ user_form|crispy }}
    {{ profile_form|crispy }}
    <button type="submit" class="btn btn-outline-primary">Save</button>
  </form>
{% endblock %}