social_app/apps/follows/urls.py
from django.urls import path
from .views import UserListView, FollowUserView, FollowingListView, UnfollowUserView, FollowerListView, RemoveFollowerView

app_name = 'follows'

urlpatterns = [
    path('users/', UserListView.as_view(), name='user-list'),
    path('follow/', FollowUserView.as_view(), name='follow-user'),
    path('following/', FollowingListView.as_view(), name='following-list'),
    path('unfollow/', UnfollowUserView.as_view(), name='unfollow-user'),
    path('followers/', FollowerListView.as_view(), name='follower-list'),
    path('remove-follower/', RemoveFollowerView.as_view(), name='remove-follower'),
]

social_app/social_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('user_auth/', include('apps.user_authentication.urls', namespace='user_auth')),
    path('user_profile/', include('apps.user_profile.urls', namespace='user_profile')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('follows/', include('apps.follows.urls', namespace='follows')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_app/apps/follows/models.py
from django.db import models
from django.contrib.auth.models import User

class Follow(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    created_at = models.DateTimeField(auto_now_add=True)

social_app/apps/follows/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, View
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Follow


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'follows/user_list.html'
    context_object_name = 'users'

    def get_queryset(self):
        current_user = self.request.user

        # Exclude users that the current user is already following
        queryset = User.objects.exclude(id__in=Follow.objects.filter(from_user=current_user).values('to_user'))

        # Exclude the superuser from the queryset
        queryset = queryset.exclude(is_superuser=True)

        # Exclude the current user from the queryset
        queryset = queryset.exclude(id=current_user.id)

        return queryset


class FollowingListView(LoginRequiredMixin, ListView):
    model = Follow
    template_name = 'follows/following_list.html'
    context_object_name = 'following'
    extra_context = {}

    def get_queryset(self):
        current_user = self.request.user
        queryset = Follow.objects.filter(from_user=current_user)
        self.extra_context['following_count'] = queryset.count()
        return queryset
    

class FollowerListView(LoginRequiredMixin, ListView):
    model = Follow
    template_name = 'follows/follower_list.html'
    context_object_name = 'followers'
    extra_context = {}
    
    def get_queryset(self):
        current_user = self.request.user
        queryset = Follow.objects.filter(to_user=current_user)
        self.extra_context['followers_count'] = queryset.count()
        return queryset
    

class FollowUserView(LoginRequiredMixin, View):
    def post(self, request):
        from_user_id = request.POST.get('from_user_id')
        to_user_id = request.POST.get('to_user_id')

        # Create a new entry in the Follow model
        follow = Follow.objects.create(
            from_user_id=from_user_id,
            to_user_id=to_user_id
        )

        return redirect('follows:user-list')  # Redirect to the recommend page after following


class UnfollowUserView(LoginRequiredMixin, View):
    def post(self, request):
        from_user_id = request.POST.get('from_user_id')
        to_user_id = request.POST.get('to_user_id')

        # Retrieve the Follow object and delete it
        try:
            follow = Follow.objects.get(from_user_id=from_user_id, to_user_id=to_user_id)
            follow.delete()
        except Follow.DoesNotExist:
            pass

        return redirect('follows:following-list')
    
class RemoveFollowerView(View):
    def post(self, request):
        from_user_id = request.POST.get('from_user_id')
        to_user_id = request.POST.get('to_user_id')

        # Retrieve the Follow object and delete it
        try:
            follow = Follow.objects.get(from_user_id=from_user_id, to_user_id=to_user_id)
            follow.delete()
        except Follow.DoesNotExist:
            pass

        return redirect('follows:follower-list')

social_app/templates/follows/follower_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/margin-style.css' %}">
{% endblock %}

{% block content %}
<div class="margin margin-sm margin-md margin-lg">
  <h1>{{ followers_count }} Followers</h1>

  {% for follower in followers %}
  <div class="card text-white bg-primary mt-3 mb-3 w-100">
    <div class="d-flex align-items-center justify-content-between m-2">
      <div class="d-flex align-items-center">
        {% if follower.from_user.profile.profile_picture %}
          {% if follower.from_user.profile.profile_picture.width == follower.from_user.profile.profile_picture.height %}
          <div style="width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
            <img src="{{ follower.from_user.profile.profile_picture.url }}" alt="{{ follower.from_user.username }}'s Profile Picture" style="width: 100%; height: 100%; object-fit: cover; border-radius: 50%;">
          </div>
          {% else %}
          <div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
            <img src="{{ follower.from_user.profile.profile_picture.url }}" alt="{{ follower.from_user.username }}'s Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">
          </div>
          {% endif %}
        {% else %}
        <img src="/media/profile_pictures/default.jpg" alt="{{ follower.from_user.username }}'s Default Picture" style="width: 50px; border-radius: 50%; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
        {% endif %}
        <span class="mx-3">{{ follower.from_user.username }}</span>
      </div>
      <div class="">
        <form action="{% url 'follows:remove-follower' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="from_user_id" value="{{ follower.from_user.id }}">
          <input type="hidden" name="to_user_id" value="{{ request.user.id }}">
          <button type="submit" class="btn btn-outline-danger">Remove  <i class="fa-solid fa-minus"></i></button>
        </form>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

social_app/templates/follows/following_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/margin-style.css' %}">
{% endblock %}

{% block content %}
<div class="margin margin-sm margin-md margin-lg">
  <h1>{{ following_count }} Following</h1>

  {% for follow in following %}
  <div class="card text-white bg-primary mt-3 mb-3 w-100">
    <div class="d-flex align-items-center justify-content-between m-2">
      <div class="d-flex align-items-center">
        {% if follow.to_user.profile.profile_picture %}
          {% if follow.to_user.profile.profile_picture.width == follow.to_user.profile.profile_picture.height %}
          <div style="width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
            <img src="{{ follow.to_user.profile.profile_picture.url }}" alt="{{ follow.to_user.username }}'s Profile Picture" style="width: 100%; height: 100%; object-fit: cover; border-radius: 50%;">
          </div>
          {% else %}
          <div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
            <img src="{{ follow.to_user.profile.profile_picture.url }}" alt="{{ follow.to_user.username }}'s Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">
          </div>
          {% endif %}
        {% else %}
        <img src="/media/profile_pictures/default.jpg" alt="{{ follow.to_user.username }}'s Default Picture" style="width: 50px; border-radius: 50%; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
        {% endif %}
        <span class="mx-3">{{ follow.to_user.username }}</span>
      </div>
      <div class="">
        <form action="{% url 'follows:unfollow-user' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="from_user_id" value="{{ request.user.id }}">
          <input type="hidden" name="to_user_id" value="{{ follow.to_user.id }}">
          <button type="submit" class="btn btn-outline-danger">Unfollow  <i class="fa-solid fa-minus"></i></button>
        </form>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

social_app/templates/follows/user_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/margin-style.css' %}">
{% endblock %}

{% block content %}
<div class="margin margin-sm margin-md margin-lg">
  <h1>User List</h1>

  {% for user in users %}
  <div class="card text-white bg-primary mt-3 mb-3 w-100">
    <div class="d-flex align-items-center justify-content-between m-2">
      <div class="d-flex align-items-center">
        {% if user.profile.profile_picture %}
          {% if user.profile.profile_picture.width == user.profile.profile_picture.height %}
          <div style="width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
            <img src="{{ user.profile.profile_picture.url }}" alt="{{ user.username }}'s Profile Picture" style="width: 100%; height: 100%; object-fit: cover; border-radius: 50%;">
          </div>
          {% else %}
          <div style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
            <img src="{{ user.profile.profile_picture.url }}" alt="{{ user.username }}'s Profile Picture" style="max-width: 100%; max-height: 100%; object-fit: contain;">
          </div>
          {% endif %}
        {% else %}
        <img src="/media/profile_pictures/default.jpg" alt="{{ user.username }}'s Default Picture" style="width: 50px; border-radius: 50%; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);">
        {% endif %}
        <span class="mx-3">{{ user.username }}</span>
      </div>
      <div class="">
        <form action="{% url 'follows:follow-user' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="from_user_id" value="{{ request.user.id }}">
          <input type="hidden" name="to_user_id" value="{{ user.id }}">
          <button type="submit" class="btn btn-outline-success">Follow  <i class="fa-solid fa-plus"></i></button>
        </form>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}